### ISSUE TITLE
bj_bus.py 39,57行

### ISSUE THREAD

**Issue by orangle** [python-cn/slack_bot#30]
[bj_bus.py](https://github.com/python-cn/slack_bot/blob/master/slack_bot/plugins/bj_bus.py)

39,57行

```
 for i in range(len(raw_bytes)):
                k = (255L & (k + 1L))
                j = (255L & (j + trans_table[k]))
                [trans_table[j], trans_table[k]] = [
                    trans_table[k], trans_table[j]]
                [trans_table[j], trans_table[k]]
                n = (255L & (trans_table[k] + trans_table[j]))
                ret_val[i] = (raw_bytes[i] ^ trans_table[n])
                ret_val[i]
```

这一句 `[trans_table[j], trans_table[k]]` 作用是啥？ 有点迷惑

**Comment by dongweiming** [comment]
这是从原作者哪里拿来的. 简单处理了下. 这明显没用. 你上次说的不支持带汉字的线路 比如`运通101` 解决的时候一起修改掉

**Comment by dongweiming** [comment]
我个人不会反编译. 后来请安卓的同学简单地反编译了下<北京实时公交>. 发现使用了不同的api. 但是线路的id是被某种算法定制之后的了. 我没有能力搞定. 我给原作者提了个[issue](https://github.com/andelf/beijing-realtime-bus/issues/2)

**Comment by dongweiming** [comment]
@orangle  你得再等等. 我们看看有没有什么方式 解决这个问题 暂时Pending了

**Comment by andelf** [comment]
我简单解释下。
这个公交的部分数据是被简单加密过的，以上的那段代码是用来解密字符串的。
算法来自于反编译。
最初是用 Hy 语言写的（Python VM 上的 Lisp 方言）https://github.com/andelf/beijing-realtime-bus/blob/master/bjgj.hy 直接输出为 Python 代码。所以你看到的Python代码语法诡异，很多无意义表达式。

**Comment by andelf** [comment]
这个文件我来改吧。:)

**Comment by dongweiming** [comment]
@andelf 非常感谢. 辛苦了!

**Comment by andelf** [comment]
存在问题：
- 原有API代码不够清晰, my bad :( 
- 对公交ID的处理逻辑错误，所以站点数据不正确

我打算按照 App 的逻辑重写~

另外，你们打算如何处理上下行（一个公交线路是两个方向）

**Comment by dongweiming** [comment]
@andelf 感谢. 目前我们没有处理上下行, 站点信息就是默认返回的顺序. 实时公交就是根据该站点距离排序列出来， 因为其中有一个下站名字, 是可以标示出来这个方向的.

**Comment by andelf** [comment]
如果这样的话，聊天指令也得说明自己的目的方向才行？

**Comment by andelf** [comment]
API中一条线路是一分为二的，并没有合并，也就是说
上行的线路和下行的线路做两条线路处理。所以？

**Comment by dongweiming** [comment]
我看到这个问题了. 每个公交线路其实都有2个符合结果. 一个是上行，一个是下行. 我设想是不增加指令的复杂度和对话次数. 比如找997, 就会把id 81和id 135 的结果都取出来. 每行 分成3列.  分别是: 站点名字; 线路一(81)的站点id; 线路2的站点id.  有点table的感觉 - 第一行加上一个thead 包含这个线路的id, 

当查询实时站点时候, 可选的指定线路的id, 比如81和135. 这样就只获取一个线路的情况. 否则是上下行全部的根据距离排序的结果.

**Comment by andelf** [comment]
OK, 懂你意思了。今晚发你PR
