### ISSUE TITLE
能在setting文件里加上注释吗

### ISSUE THREAD

**Issue by firemiles** [python-cn/slack_bot#44]
setting文件里的配置参数没有注释说明，很多配置的作用和内容不太搞得清楚，如果能加上注释说明就好了。

**Comment by halfcrazy** [comment]
@firemiles 比如呢？

**Comment by firemiles** [comment]
REDIS_URL这个参数配置redis，不太清楚哪里需要用到redis，不配置好像也没问题。
还有BAIDU_AK，我猜测是用来使用百度地图的，不知道对不对，但是能有个简单的说明感觉更容易上手。
PS: 我对这些服务的使用不是很熟悉，所以比较迷惑。

**Comment by dongweiming** [comment]
@firemiles  好 我来处理下

**Comment by firemiles** [comment]
@dongweiming 谢谢

**Comment by firemiles** [comment]
@dongweiming 介绍的很清楚，这下把用到的服务都搞明白了。
