### ISSUE TITLE
movie插件经常超时

### ISSUE THREAD

**Issue by firemiles** [python-cn/slack_bot#46]
movie插件的返回经常会超过Heroku限定的30s，导致Heroku返回503错误。
建议给插件加上超时机制

**Comment by dongweiming** [comment]
movie超时的主要原因是豆瓣电影的图片做了防盗链的策略, 不能直接在slack里面显示, 所以我的做法是,下载图片, 把它传到slack的文件服务器上, 然后获得返回的url. 大部分的时间都浪费在下载和上传图片的时候.

我当时研究过改这个超时, 但是没有找到对应的设置方式

**Comment by halfcrazy** [comment]
@firemiles @dongweiming 如果是heroku那边的超时，参考 https://devcenter.heroku.com/articles/request-timeout 这里有说明可以设置超时时间

或者在flask-slackbot这层，加一个handle超时处理的支持

**Comment by dongweiming** [comment]
@halfcrazy 你说的这个页面没有对我们这种环境的配置

**Comment by halfcrazy** [comment]
@dongweiming PROC文件`web: gunicorn wsgi:app --timeout 240 --log-file -`这里的`--timeout 240`，在heroku上是没用的，最大是30s，也就是默认的timeout。

> By default, Gunicorn gracefully restarts a worker if hasn’t completed any work within the last 30 seconds.

**Comment by dongweiming** [comment]
我后来给heroku的帮助中心发了邮件, 问怎么修改. 它们给的回复是没法修改, 我们只能自己优化解决. 

> Hi,
> 
> 30s timeout is Heroku router level timeout, so you can't use anything longer even though it's technically >configurable with Gunicorn (and I think your Gunicorn is actually using your timeout, but the response >just doesn't reach to the client because Heroku router already made a response with H12 errors). You'll >see H12 errors for any requests that take more than 30s as Steven explained, it's a hard limit of Heroku >platform and we can't extend this, unfortunately.
> 
> If you expect the request to be more than 30s, you'll need to optimize it or find some workaround.
> 
> Best,
> Keiko
